# Generated by Django 4.1.2 on 2022-10-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='endereco',
            field=models.CharField(max_length=50, verbose_name='endereço'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='numero',
            field=models.CharField(max_length=5, verbose_name='número'),
        ),
    ]
