# Generated by Django 4.1.2 on 2022-10-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='qtd_total',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
